# Generated by Django 4.2.1 on 2023-06-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_name',
            new_name='dept_no',
        ),
    ]
